name = "Rho2sdf"
uuid = "94e57e3a-8545-4178-8785-fc7fba63f629"
authors = ["Ján Kopačka <J.Kopacka@seznam.cz>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
BenchmarkTools = "1.6.0"
CairoMakie = "0.13.1"
Einsum = "0.4.1"
FastGaussQuadrature = "1.0.2"
GLMakie = "0.11.2"
GeometryBasics = "0.5.2"
Ipopt = "1.7.1"
IterativeSolvers = "0.9.4"
JLD2 = "0.5.11"
JuMP = "1.23.6"
KernelFunctions = "0.10.64"
MAT = "0.10.7"
Makie = "0.22.1"
NLopt = "1.1.2"
NearestNeighbors = "0.4.21"
ProgressMeter = "1.10.2"
ReadVTK = "0.2.4"
StaticArrays = "1.9.10"
WriteVTK = "1.21.1"
